<?php
/*
|--------------------------------------------------------------------------
| Cdn link in our faveo
|--------------------------------------------------------------------------
|
| This option controls the default cdn
|
|
|
 */
return [
    'image' => [
        'logo'         =>'https://cdn.faveohelpdesk.com/themes/default/common/images/logo.png',
        'favicon'      =>'https://cdn.faveohelpdesk.com/themes/default/common/images/favicon.ico',
        'whitefavicon' =>'https://cdn.faveohelpdesk.com/themes/default/common/images/whitefavicon.png',
        'loading'      =>'https://cdn.faveohelpdesk.com/themes/default/agent/images/loading.gif',
        'gifloader'    =>'https://cdn.faveohelpdesk.com/themes/default/common/images/gifloader.gif',
        'gifloader3'   =>'https://cdn.faveohelpdesk.com/themes/default/common/images/gifloader3.gif',
        'whitelabel'   =>'https://cdn.faveohelpdesk.com/themes/default/common/images/whitelabel.png',
        'nodatafound'  =>'https://cdn.faveohelpdesk.com/themes/default/agent/images/nodatafound.png',
        'faveo'        =>'https://cdn.faveohelpdesk.com/themes/default/common/images/installer/faveo.png',
        'team'         =>'https://cdn.faveohelpdesk.com/themes/default/admin/images/team.jpg',
        'department'   =>'https://cdn.faveohelpdesk.com/themes/default/admin/images/department.jpg',
        '25'           =>'https://cdn.faveohelpdesk.com/themes/default/admin/images/25.gif',
        'system'       =>'https://cdn.faveohelpdesk.com/themes/default/common/images/system.png',
        'text'         =>'https://cdn.faveohelpdesk.com/themes/default/agent/images/text.png',
        'common'       =>'https://cdn.faveohelpdesk.com/themes/default/agent/images/common.png',
        'flag'         =>'https://cdn.faveohelpdesk.com/themes/default/common/images/flags',
        'knowledgebase'=>'https://cdn.faveohelpdesk.com/themes/default/client/images/knowledgebase.png',
        'register'     =>'https://cdn.faveohelpdesk.com/themes/default/client/images/register.png',
        'news'         =>'https://cdn.faveohelpdesk.com/themes/default/client/images/news.png',
        'submitticket' =>'https://cdn.faveohelpdesk.com/themes/default/client/images/submitticket.png',
        'video'        =>'https://cdn.faveohelpdesk.com/themes/default/common/images/video.png',
        'audio'        =>'https://cdn.faveohelpdesk.com/themes/default/common/images/audio.png',
        'contacthead'  =>'https://cdn.faveohelpdesk.com/themes/default/common/images/contacthead.png',
        'logo-presidencia' =>'https://cdn.faveohelpdesk.com/themes/default/client/images/Logo-presidencia-blanco.png',
    ],
    'css'   => [
        'all-skins'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/css/_all-skins.min.css',
        'admin-common'              => 'https://cdn.faveohelpdesk.com/themes/default/admin/css/admin-common.css',
        'AdminLTE'                  => 'https://cdn.faveohelpdesk.com/themes/default/common/css/AdminLTE.min.css',
        'AdminLTEsemi'              => 'https://cdn.faveohelpdesk.com/themes/default/common/css/AdminLTEsemi.min.css',
        'bootstrap'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap.min.css',
        'bootstrap-latest'          => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap-v3.4.min.css',
        'bootstrap-datetimepicker4' => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap-datetimepicker4.7.14.min.css',
        'bootstrap-multiselect'     => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap-multiselect.css',
        'bootstrap-select'          => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap-select.css',
        'bootstrap-toggle'          => 'https://cdn.faveohelpdesk.com/themes/default/admin/css/bootstrap-toggle.min.css',
        'bootstrap-select-min'      => 'https://cdn.faveohelpdesk.com/themes/default/common/css/min/bootstrap-select.css',
        'font-awesome'              => 'https://cdn.faveohelpdesk.com/themes/default/common/css/font-awesome.min.css',
        'jquerysctipttop'           => 'https://cdn.faveohelpdesk.com/themes/default/client/css/jquerysctipttop.min.css',
        'ionicons'                  => 'https://cdn.faveohelpdesk.com/themes/default/common/css/ionicons.min.css',
        'tabby'                     => 'https://cdn.faveohelpdesk.com/themes/default/common/css/tabby.min.css',
        'editor'                    => 'https://cdn.faveohelpdesk.com/themes/default/common/css/editor.css',
        'new-common'                => 'https://cdn.faveohelpdesk.com/themes/default/agent/css/new-common.min.css',
        'nprogress'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/css/loader/nprogress.min.css',
        'widgetbox'                 => 'https://cdn.faveohelpdesk.com/themes/default/client/css/widgetbox.min.css',
        'jquery-rating'             => 'https://cdn.faveohelpdesk.com/themes/default/common/css/jquery.rating.min.css',
        'jquery-ui'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/css/jquery.ui.css',
        'flags'                     => 'https://cdn.faveohelpdesk.com/themes/default/client/css/flags.min.css',
        'client-custom-css'        => 'https://cdn.faveohelpdesk.com/themes/default/client/css/client.min.css',
        'faveo-css'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/css/faveo-css.css',
        'select2'                   => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/select2/select2.min.css',
        'bootstrap-switch'          => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/bootstrap_switch/bootstrap-switch.css',
        'bootstrap-switch-min'      => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/bootstrap_switch/bootstrap-switch.min.css',
        'daterangepicker'           => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/daterangepicker/daterangepicker.css',
        'daterangepicker'           => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/daterangepicker/daterangepicker.css',
        'dataTables-bootstrap'      => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/datatables/dataTables.bootstrap.min.css',
         'blue'                     => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/iCheck/flat/blue.css',
        'bootstrap-colorpicker'     => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/colorpicker/bootstrap-colorpicker.min.css',
        'jquery-ui-base-1'          => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/hailhood-tag/demo/css/jquery-ui-base-1.8.20.css',
        'tagit-stylish-yellow'      => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/hailhood-tag/css/tagit-stylish-yellow.css',
        'intlTelInput'              => 'https://cdn.faveohelpdesk.com/themes/default/common/css/intlTelInput.min.css',
        'app'                       => 'https://cdn.faveohelpdesk.com/themes/default/admin/css/app.css',
        'app-form'                  =>'https://cdn.faveohelpdesk.com/themes/default/admin/css/form/app.css',
        'angular-ui-tree'           => 'https://cdn.faveohelpdesk.com/themes/default/admin/css/angular-ui-tree.css',
        'load-styles'               =>'https://cdn.faveohelpdesk.com/themes/default/common/css/load-styles.css',
        'css'                       =>'https://cdn.faveohelpdesk.com/themes/default/common/css/css.css',
        'admin'                     =>'https://cdn.faveohelpdesk.com/themes/default/common/css/admin.css',
        'setup'                     =>'https://cdn.faveohelpdesk.com/themes/default/common/css/setup.css',
        'activation'                =>'https://cdn.faveohelpdesk.com/themes/default/common/css/activation.css',
        'style'                     =>'https://cdn.faveohelpdesk.com/themes/default/common/css/style.css',
        'ggpopover'                 =>'https://cdn.faveohelpdesk.com/themes/default/common/css/ggpopover.css',
        'prism'                     =>'https://cdn.faveohelpdesk.com/themes/default/common/css/prism.css',
        'chosen'                    =>'https://cdn.faveohelpdesk.com/themes/default/common/css/chosen.css',
        'fullcalendar'              =>'https://cdn.faveohelpdesk.com/themes/default/agent/plugins/fullcalendar/fullcalendar.min.css',
        'tw-currency-select'        =>'https://cdn.faveohelpdesk.com/themes/default/common/plugins/currency-picker/tw-currency-select.css',
        'widgetbox'                 =>'https://cdn.faveohelpdesk.com/themes/default/client/css/widgetbox.min.css',
        'faveo-css'                 =>'https://cdn.faveohelpdesk.com/themes/default/common/css/faveo-css.css',
        'star'                      =>'https://cdn.faveohelpdesk.com/themes/default/agent/images/star.png',
        

        'ckeditor-css'              =>'https://cdn.faveohelpdesk.com/themes/default/common/plugins/ckeditor5/ckeditor.css',

        //===================================================
        //servicedesk plugin
        //=====================================================
        'perfect-scrollbar'         =>'https://cdn.faveohelpdesk.com/themes/default/common/css/perfect-scrollbar.css',
        'table-style'               =>'https://cdn.faveohelpdesk.com/themes/default/agent/css/perfect-scrollbar.css',
        'bootstrap-rtl'             =>'https://cdn.faveohelpdesk.com/themes/default/common/css/rtl/css/bootstrap-rtl.min.css',
        //===================================================
        
        // LATEST VERSIONS
        // Font Awesome && Bootstrap
        'bootstrap-4'                => 'https://cdn.faveohelpdesk.com/themes/default/common/css/bootstrap4.min.css',
        'font-awesome-5'             => 'https://cdn.faveohelpdesk.com/themes/default/common/css/font-awesome5.min.css',
        'new-overlay'           => 'https://cdn.faveohelpdesk.com/themes/default/common/adminlte3/plugins/overlayScrollbars/overlayScrollbars.min.css',
        'adminlte-3'                  => 'https://cdn.faveohelpdesk.com/themes/default/common/adminlte3/css/adminlte3.min.css',
        'adminlte-3-rtl'                  => 'https://cdn.faveohelpdesk.com/themes/default/common/adminlte3/rtl/adminlte3.min.css',
        
    ],
    'js'    => [
        'moment'                       => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/moment.min.js',
        'chart'                        => 'https://cdn.faveohelpdesk.com/themes/default/agent/js/min/Chart.min.js',
        'bootstrap'                    => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/bootstrap.min.js',
        'bootstrap-latest'        => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/bootstrap-v3.4.min.js',
        'bootstrap-toggle'             => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/bootstrap-toggle.min.js',
        'bootstrap-select'             => 'https://cdn.faveohelpdesk.com/themes/default/common/js/bootstrap-select.js',
        'ui-bootstrap-tpls'            => 'https://cdn.faveohelpdesk.com/themes/default/common/js/ui-bootstrap-tpls-1.2.5.js',
        'polyfill'                     => 'https://cdn.faveohelpdesk.com/themes/default/client/js/min/polyfill.min.js',
        'jquery-2'                     => 'https://cdn.faveohelpdesk.com/themes/default/common/js/jquery-2.1.4.min.js',
        'angular'                      => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/angular.min.js',
        'angular-moment'               => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/angular-moment.min.js',
        'bsSwitch'                     => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/bsSwitch.js',
        'angular-desktop-notification' => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/angular-desktop-notification.min.js',
        'ui-bootstrap-tpls'            => 'https://cdn.faveohelpdesk.com/themes/default/common/js/form/ui-bootstrap-tpls.js',
        'main'                         => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/main.js',
        'handleCtrl'                   => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/handleCtrl.js',
        'nodeCtrl'                     => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/nodeCtrl.js',
        'nodesCtrl'                    => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/nodesCtrl.js',
        'treeCtrl'                     => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/treeCtrl.js',
        'uiTree'                       => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/uiTree.js',
        'uiTreeHandle'                 => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/uiTreeHandle.js',
        'uiTreeNode'                   => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/uiTreeNode.js',
        'uiTreeNodes'                  => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/uiTreeNodes.js',
        'helper'                       => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/form/helper.min.js',
        'ng-flow-standalone'           => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/ng-flow-standalone.js',
        'fusty-flow'                   => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/fusty-flow.min.js',
        'fusty-flow-factory'           => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/fusty-flow-factory.min.js',
        'ng-file-upload'               => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/ng-file-upload.min.js',
        'ng-file-upload-shim'          => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/ng-file-upload-shim.min.js',
        'superfish'                    => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/superfish.min.js',
        'mobilemenu'                   => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/mobilemenu.min.js',
        'know'                         => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/know.min.js',
        'app-min'                      => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/app.min.js',
        'intlTelInput'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/js/intlTelInput.js',
        'bootstrap-datetimepicker4'    => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/bootstrap-datetimepicker4.7.14.min.js',
        'jquery-ui'                    => 'https://cdn.faveohelpdesk.com/themes/default/common/js/jquery.ui.js',
        'bootstrap-multiselect'        => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/bootstrap-multiselect.js',
        'angular-admin-script'         => 'https://cdn.faveohelpdesk.com/themes/default/admin/js/angular-admin-script.js',
        'tabby'                        => 'https://cdn.faveohelpdesk.com/themes/default/agent/js/min/tabby.min.js',
        'angular-recaptcha'            => 'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/angular-recaptcha.min.js',
        'select2'                      => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/select2/select2.min.js',
        'jquery-dataTables'            => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/datatables/jquery.dataTables.min.js',
        'bootstrap-switch'             => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/bootstrap_switch/bootstrap-switch.js',
        'bootstrap-switch-min'         => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/bootstrap_switch/bootstrap-switch.min.js',
        'chart-min'                    => 'https://cdn.faveohelpdesk.com/themes/default/agent/plugins/chartjs/Chart.min.js',
        'jquery'                       => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/jQuery/jquery-3.1.1.min.js',
        'jquery-3'                       => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/jQuery/jquery-3.4.1.min.js',
        'daterangepicker'              => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/daterangepicker/daterangepicker.js',
        'daterangepicker-min'          =>'https://cdn.faveohelpdesk.com/themes/default/common/plugins/daterangepicker/daterangepicker.min.js',
        'moment-timezone'              => 'https://cdn.faveohelpdesk.com/themes/default/agent/plugins/moment/moment-timezone.min.js',
        'moment-timezone-with-data'    => 'https://cdn.faveohelpdesk.com/themes/default/agent/plugins/moment/moment-timezone-with-data-2012-2022.min.js',
        'ckeditor'                     => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/ckeditor4/ckeditor.js',
        'vue-ckeditor'                 => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/ckeditor5/ckeditor.js',
        'app'                          => 'https://cdn.faveohelpdesk.com/themes/default/client/js/app.js',
        'nprogress'                    => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/loader/nprogress.min.js',
        'tw-currency-select'           => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/currency-picker/tw-currency-select.min.js',
        'browser-detect'               => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/browser-detect.min.js',
        'dataTables-bootstrap'         => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/datatables/dataTables.bootstrap.min.js',
        'iCheck'                       => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/iCheck/icheck.min.js',
        'bootstrap-colorpicker'        => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/colorpicker/bootstrap-colorpicker.min.js',
        'tagit'                        => 'https://cdn.faveohelpdesk.com/themes/default/admin/plugins/hailhood-tag/js/tagit.js',
        'bootstrap3-wysihtml5'         => 'https://cdn.faveohelpdesk.com/themes/default/common/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js',
        'angular-agent-scripts'        =>'https://cdn.faveohelpdesk.com/themes/default/agent/js/angular-agent-scripts.js',
        'ggpopover'                    =>'https://cdn.faveohelpdesk.com/themes/default/common/js/ggpopover.js',
        'chosen-jquery'                =>'https://cdn.faveohelpdesk.com/themes/default/common/js/chosen.jquery.js',
        'prism'                        =>'https://cdn.faveohelpdesk.com/themes/default/common/js/prism.js',
        'jquery-sticky'                =>'https://cdn.faveohelpdesk.com/themes/default/admin/js/jquery.sticky.js',
        'utils'                        =>'https://cdn.faveohelpdesk.com/themes/default/client/js/min/utils.min.js',
        'select2-full-min'             =>'https://cdn.faveohelpdesk.com/themes/default/common/plugins/select2/select2.full.min.js',
        'fullcalendar'                 =>'https://cdn.faveohelpdesk.com/themes/default/agent/plugins/fullcalendar/fullcalendar.min.js',
        'ajax-jquery'                  =>'https://cdn.faveohelpdesk.com/themes/default/admin/min/js/ajax-jquery.min.js',
        'jquery-rating-pack'           =>'https://cdn.faveohelpdesk.com/themes/default/common/js/jquery.rating.pack.min.js',
        'utils'                        =>'https://cdn.faveohelpdesk.com/themes/default/common/js/utils.js',
        'angular2'                     =>'https://cdn.faveohelpdesk.com/themes/default/common/js/angular/angular2.js',
        




        //===================================================
        //servicedesk plugin
        //=====================================================
        'perfect-scrollbar'            =>'https://cdn.faveohelpdesk.com/themes/default/common/js/perfect-scrollbar.js',
        'jquery-twbsPagination'        =>'https://cdn.faveohelpdesk.com/themes/default/agent/js/jquery.twbsPagination.js',
        'jquery-slimscroll'            =>'https://cdn.faveohelpdesk.com/themes/default/admin/js/min/jquery.slimscroll.min.js',
        'fastclick'                    =>'https://cdn.faveohelpdesk.com/themes/default/admin/js/min/fastclick.min.js',
        'plugin'                       =>'https://cdn.faveohelpdesk.com/themes/default/admin/js/plugin.js',
        //=====================================================
        
        // BOOTSTRAP LATEST
        'bootstrap-4'                   => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/bootstrap4.min.js',

        'client-custom-js' => 'https://cdn.faveohelpdesk.com/themes/default/client/js/min/client.min.js',
        'popper' => 'https://cdn.faveohelpdesk.com/themes/default/common/js/min/popper.min.js',
        'laravel-echo'                  =>'https://cdn.faveohelpdesk.com/themes/default/common/js/min/echo.min.js',
        'pusher'                        =>'https://cdn.faveohelpdesk.com/themes/default/common/js/min/pusher.js',
         'new-overlay'           => 'https://cdn.faveohelpdesk.com/themes/default/common/adminlte3/plugins/overlayScrollbars/overlayScrollbars.min.js',
        'adminlte-3'                  => 'https://cdn.faveohelpdesk.com/themes/default/common/adminlte3/js/adminlte3.min.js',
    ],
];
